### ISSUE TITLE
Availability of raw Illumina fastq

### ISSUE THREAD

**Issue by adcosta17** [human-pangenomics/HPP_Year1_Data_Freeze_v1.0#2]
Hi, 

I noticed that in the Data Layout section Illumina is listed under Raw Data for samples in the HPRC section. 
Only the CRAM files are listed in the repository and not the raw fastqs. Are the fastqs available for download? 

Thanks, 
Alister

**Comment by juklucas** [comment]
That is a good point, for almost all of the samples we are storing CRAM files from 1000G. In our assembly workflows, we use the [extract_reads.wdl](https://github.com/human-pangenomics/hpp_production_workflows/blob/master/QC/wdl/tasks/extract_reads.wdl) to dump the CRAMs to fastqs with a ```samtools fastq``` call. We could store the fastq files, I guess, they would just be large. Let me talk to the team about whether or not it would make sense to store this data in fastq format.

**Comment by juklucas** [comment]
Hi Alister, 

We talked internally, and at this time it looks like we will hold off on storing the fastq versions of these files for now (to save on space).

I added [better documentation](https://github.com/human-pangenomics/HPP_Year1_Data_Freeze_v1.0/commit/e24d34b09a1559bda8cce81c0ccd89ebc6e321a8) to help clarify the Illumina datasets. Thanks for the request.

-Julian

**Comment by adcosta17** [comment]
Thanks for the update!
