### ISSUE TITLE
Guidance for Bionano data visualization

### ISSUE THREAD

**Issue by sachalau** [human-pangenomics/HPP_Year1_Data_Freeze_v1.0#3]
Dear human pangenomics consortium,

Thank you so much for putting such a wealth of data into the public domain !  I've used the PacBio data to investigate CNV on the STRC-STRCP1 locus, and how we can detect them using the PacBio data. FYI I extracted the reads on these regions then assembled the data with HifiASM to reconstruct the two haplotypes.

Doing so, I identified an heterozygous deletion of CKMT1B-STRC-CATSPER2 on HG02630 (on NA019240 as well, which was well known, see: http://dgv.tcag.ca/gb2/gbrowse_details/dgv2_hg19?ref=chr15;start=43845410;end=44024490;name=gssvL39070;class=Sequence;feature_id=15307;db_id=hg19_dgvgold%3Adatabase). Then I would be very interested to check that the BioNano data shows the same deletion. However, I'm not able to access Bionano proprietary software analysis and visualization tools. 

I've seen that you refer to the BioNano website regarding the visualization and analysis of their data, but I was wondering if you have specific tips for open access tools in order to visualize the information on this specific region (15q15.3) for this sample? 

Thanks a lot for your help

**Comment by juklucas** [comment]
Bionano access has a genome viewer and mapper integrated: https://bionanogenomics.com/support-page/bionano-access-software/. It is free and can be installed locally. Hope this helps.

**Comment by sachalau** [comment]
Thanks for the answer ! Indeed donwloading BioNano Access is free after redeeming its personal information to BioNano, I'll try to convert the cmap file into an "Alignment" from the CLI tool and visualize the result with BioNano Access.

Edit: I've managed ! I could perform the Map Alignment and visualize the region on BioNano Access, confirming the deletion seen with HiFi data. Thanks a lot for your help.

**Comment by sachalau** [comment]
Thanks again for your answer !

I've managed to have a BioNano Access instance running on my own computer and I could import the Molecules (bnx.gz) and Map (cmap) files.

However, I can't perform any analysis on these files without installing BioNano Solve, for performing all the computations. Although the installation of Access was quite straightforward, Solve seems to be quite different in complexity, necessitating apparently a Sun Grid Engine (SGE) installation etc, which I think is inaccessible to most users.

As such I don't think that the data shared for BioNano will be usable by third parties without access to a BioNano Solve compute node. However, according to the documentation (https://bionanogenomics.com/wp-content/uploads/2018/04/30142-Bionano-Access-Software-User-Guide.pdf), the following "Job Types" could be imported directly into BioNano Access for visualization ("Viewer"):

1. Assembly (zip)
2. Alignment (reference cmap + alignment xmap + query cmap)
3. Rare Variant Analysis (zip)
4. Variant Annotation Pipeline (zip)
5. Scaffold (zip)

Is there any chance that you could consider sharing these files as well for the HPRC data ? I'm interested in particular by HG02630 but I think that many users without access to BioNano Solve compute could be interested in these data.

Best,

**Comment by juklucas** [comment]
Glad to hear it!
